import MatrixSpencer.DensityPotential

/-!
# The source generated by the actual coefficient covariance

The covariance is a real symmetric positive matrix. Its bilinear source is
identified with a concrete Kraus family obtained by its positive square root.
-/

open scoped BigOperators Matrix MatrixOrder ComplexOrder
open Matrix

noncomputable section

namespace MatrixSpencer

variable {ι n : Type*} [Fintype ι] [Fintype n] [DecidableEq ι]

/-- The bilinear source in the original covariance coordinates. -/
def covarianceSource (A : ι → Matrix n n ℂ) (C : Matrix ι ι ℝ)
    (S : Matrix n n ℂ) : Matrix n n ℂ :=
  ∑ i, ∑ j, C i j • (A i * S * A j)

/-- Real coefficient mixing preserves Hermitian physical matrices. -/
def mixedKraus (A : ι → Matrix n n ℂ) (R : Matrix ι ι ℝ) (a : ι) : Matrix n n ℂ :=
  ∑ i, R i a • A i

omit [Fintype n] [DecidableEq ι] in
theorem mixedKraus_isHermitian (A : ι → Matrix n n ℂ) (R : Matrix ι ι ℝ)
    (hA : ∀ i, (A i).IsHermitian) (a : ι) : (mixedKraus A R a).IsHermitian := by
  unfold mixedKraus Matrix.IsHermitian
  rw [Matrix.conjTranspose_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [Matrix.conjTranspose_smul, star_trivial, (hA i).eq]

omit [DecidableEq ι] in
/-- Exact coefficient factorization identity, before choosing a square root. -/
theorem covarianceSource_factor (A : ι → Matrix n n ℂ) (R : Matrix ι ι ℝ)
    (hA : ∀ i, (A i).IsHermitian) (S : Matrix n n ℂ) :
    covarianceSource A (R * Rᵀ) S = krausChannel (mixedKraus A R) S := by
  have hHerm : ∀ a, (mixedKraus A R a)ᴴ = mixedKraus A R a :=
    fun a => (mixedKraus_isHermitian A R hA a).eq
  simp only [krausChannel, hHerm]
  simp only [covarianceSource, mixedKraus, Matrix.mul_apply,
    Matrix.transpose_apply, Finset.sum_smul, Matrix.sum_mul, Matrix.mul_sum,
    Matrix.smul_mul, Matrix.mul_smul, Finset.smul_sum, smul_smul]
  calc
    _ = ∑ i, ∑ a, ∑ j, (R i a * R j a) • (A i * S * A j) := by
      apply Finset.sum_congr rfl
      intro i _
      exact Finset.sum_comm
    _ = ∑ a, ∑ i, ∑ j, (R i a * R j a) • (A i * S * A j) := Finset.sum_comm
    _ = _ := by
      apply Finset.sum_congr rfl
      intro a _
      rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro j _
      apply Finset.sum_congr rfl
      intro i _
      rw [mul_comm (R i a) (R j a)]

def covarianceKraus (A : ι → Matrix n n ℂ) (C : Matrix ι ι ℝ) : ι → Matrix n n ℂ :=
  mixedKraus A (CFC.sqrt C)

theorem covarianceSqrt_factor {C : Matrix ι ι ℝ} (hC : C.PosSemidef) :
    CFC.sqrt C * (CFC.sqrt C)ᵀ = C := by
  have hs : (CFC.sqrt C)ᵀ = CFC.sqrt C := by
    simpa only [Matrix.conjTranspose_eq_transpose_of_trivial] using
      (CFC.sqrt_nonneg C).posSemidef.isHermitian.eq
  rw [hs, CFC.sqrt_mul_sqrt_self C hC.nonneg]

/-- The original covariance source is exactly a completely positive Kraus source. -/
theorem covarianceSource_eq_kraus (A : ι → Matrix n n ℂ)
    (hA : ∀ i, (A i).IsHermitian) {C : Matrix ι ι ℝ} (hC : C.PosSemidef)
    (S : Matrix n n ℂ) :
    covarianceSource A C S = krausChannel (covarianceKraus A C) S := by
  have h := covarianceSource_factor A (CFC.sqrt C) hA S
  rwa [covarianceSqrt_factor hC] at h

theorem covarianceSource_posSemidef (A : ι → Matrix n n ℂ)
    (hA : ∀ i, (A i).IsHermitian) {C : Matrix ι ι ℝ} (hC : C.PosSemidef)
    {S : Matrix n n ℂ} (hS : S.PosSemidef) : (covarianceSource A C S).PosSemidef := by
  rw [covarianceSource_eq_kraus A hA hC]
  exact krausChannel_posSemidef _ hS

omit [DecidableEq ι] in
theorem covarianceSource_add_covariance (A : ι → Matrix n n ℂ)
    (C D : Matrix ι ι ℝ) (S : Matrix n n ℂ) :
    covarianceSource A (C + D) S = covarianceSource A C S + covarianceSource A D S := by
  simp [covarianceSource, add_smul, Finset.sum_add_distrib]

omit [DecidableEq ι] in
theorem covarianceSource_sub_covariance (A : ι → Matrix n n ℂ)
    (C D : Matrix ι ι ℝ) (S : Matrix n n ℂ) :
    covarianceSource A (C - D) S = covarianceSource A C S - covarianceSource A D S := by
  simp [covarianceSource, sub_smul, Finset.sum_sub_distrib]

omit [DecidableEq ι] in
theorem covarianceSource_smul_covariance (A : ι → Matrix n n ℂ)
    (C : Matrix ι ι ℝ) (S : Matrix n n ℂ) (a : ℝ) :
    covarianceSource A (a • C) S = a • covarianceSource A C S := by
  simp [covarianceSource, Finset.smul_sum, smul_smul]

omit [DecidableEq ι] in
theorem covarianceSource_weighted_add (A : ι → Matrix n n ℂ)
    (C : Matrix ι ι ℝ) (S T : Matrix n n ℂ) (a b : ℝ) :
    covarianceSource A C (a • S + b • T) =
      a • covarianceSource A C S + b • covarianceSource A C T := by
  simp [covarianceSource, Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul,
    Matrix.smul_mul, Finset.sum_add_distrib, Finset.smul_sum, smul_add,
    smul_smul, mul_comm]

/-- Covariance order increases the actual physical source in Loewner order. -/
theorem covarianceSource_mono (A : ι → Matrix n n ℂ)
    (hA : ∀ i, (A i).IsHermitian) {C D : Matrix ι ι ℝ} (hCD : C ≤ D)
    {S : Matrix n n ℂ} (hS : S.PosSemidef) :
    covarianceSource A C S ≤ covarianceSource A D S := by
  have h := covarianceSource_posSemidef A hA (sub_nonneg.mpr hCD).posSemidef hS
  rw [covarianceSource_sub_covariance] at h
  exact sub_nonneg.mp h.nonneg

omit [DecidableEq ι] in
theorem continuous_covarianceSource (A : ι → Matrix n n ℂ) :
    Continuous (fun p : Matrix ι ι ℝ × Matrix n n ℂ => covarianceSource A p.1 p.2) := by
  unfold covarianceSource
  fun_prop

theorem covarianceSource_one (A : ι → Matrix n n ℂ) (S : Matrix n n ℂ) :
    covarianceSource A (1 : Matrix ι ι ℝ) S = ∑ i, A i * S * A i := by
  classical
  simp [covarianceSource, Matrix.one_apply]

theorem covarianceSource_one_one [DecidableEq n] (A : ι → Matrix n n ℂ) :
    covarianceSource A (1 : Matrix ι ι ℝ) (1 : Matrix n n ℂ) = ∑ i, A i * A i := by
  simp [covarianceSource_one]

omit [DecidableEq ι] in
/-- The real trace pairing is self-adjoint for a Hermitian Kraus family. -/
theorem realTrace_krausChannel_selfadjoint (B : ι → Matrix n n ℂ)
    (hB : ∀ i, (B i).IsHermitian) (S T : Matrix n n ℂ) :
    realTrace (krausChannel B S * T) = realTrace (S * krausChannel B T) := by
  simp only [krausChannel, fun i => (hB i).eq, Matrix.sum_mul, Matrix.mul_sum, realTrace_sum]
  apply Finset.sum_congr rfl
  intro i _
  simpa only [Matrix.mul_assoc] using realTrace_mul_comm (B i) (S * B i * T)

theorem realTrace_covarianceSource_selfadjoint (A : ι → Matrix n n ℂ)
    (hA : ∀ i, (A i).IsHermitian) {C : Matrix ι ι ℝ} (hC : C.PosSemidef)
    (S T : Matrix n n ℂ) :
    realTrace (covarianceSource A C S * T) = realTrace (S * covarianceSource A C T) := by
  rw [covarianceSource_eq_kraus A hA hC, covarianceSource_eq_kraus A hA hC]
  exact realTrace_krausChannel_selfadjoint _ (mixedKraus_isHermitian A _ hA) S T

end MatrixSpencer
